simulation.exe 3 3 Plurality > log\Plurality_3_3.txt
simulation.exe 3 4 Plurality > log\Plurality_3_4.txt
simulation.exe 4 3 Plurality > log\Plurality_4_3.txt
simulation.exe 4 4 Plurality > log\Plurality_4_4.txt
simulation.exe 5 3 Plurality > log\Plurality_5_3.txt
simulation.exe 5 4 Plurality > log\Plurality_5_4.txt
simulation.exe 6 3 Plurality > log\Plurality_6_3.txt
simulation.exe 7 3 Plurality > log\Plurality_7_3.txt
simulation.exe 3 3 Borda > log\Borda_3_3.txt
simulation.exe 3 4 Borda > log\Borda_3_4.txt
simulation.exe 4 3 Borda > log\Borda_4_3.txt
simulation.exe 4 4 Borda > log\Borda_4_4.txt
simulation.exe 5 3 Borda > log\Borda_5_3.txt
simulation.exe 5 4 Borda > log\Borda_5_4.txt
simulation.exe 6 3 Borda > log\Borda_6_3.txt
simulation.exe 7 3 Borda > log\Borda_7_3.txt
simulation.exe 3 3 Schulze > log\Schulze_3_3.txt
simulation.exe 3 4 Schulze > log\Schulze_3_4.txt
simulation.exe 4 3 Schulze > log\Schulze_4_3.txt
simulation.exe 4 4 Schulze > log\Schulze_4_4.txt
simulation.exe 5 3 Schulze > log\Schulze_5_3.txt
simulation.exe 5 4 Schulze > log\Schulze_5_4.txt
simulation.exe 6 3 Schulze > log\Schulze_6_3.txt
simulation.exe 7 3 Schulze > log\Schulze_7_3.txt
simulation.exe 8 3 Plurality > log\Plurality_8_3.txt
simulation.exe 8 3 Borda > log\Borda_8_3.txt
simulation.exe 8 3 Schulze > log\Schulze_8_3.txt
simulation.exe 9 3 Plurality > log\Plurality_9_3.txt
simulation.exe 9 3 Borda > log\Borda_9_3.txt
simulation.exe 9 3 Schulze > log\Schulze_9_3.txt
simulation.exe 10 3 Plurality > log\Plurality_10_3.txt
simulation.exe 10 3 Borda > log\Borda_10_3.txt
simulation.exe 10 3 Schulze > log\Schulze_10_3.txt
