filter.exe log/Borda_3_3.txt > filtered/Borda_3_3_f.txt
filter.exe log/Borda_4_3.txt > filtered/Borda_4_3_f.txt
filter.exe log/Borda_5_3.txt > filtered/Borda_5_3_f.txt
filter.exe log/Borda_6_3.txt > filtered/Borda_6_3_f.txt
filter.exe log/Borda_7_3.txt > filtered/Borda_7_3_f.txt
filter.exe log/Borda_8_3.txt > filtered/Borda_8_3_f.txt
filter.exe log/Borda_9_3.txt > filtered/Borda_9_3_f.txt
filter.exe log/Borda_10_3.txt > filtered/Borda_10_3_f.txt
filter.exe log/Borda_3_4.txt > filtered/Borda_3_4_f.txt
filter.exe log/Borda_4_4.txt > filtered/Borda_4_4_f.txt
filter.exe log/Borda_5_4.txt > filtered/Borda_5_4_f.txt
filter.exe log/Borda_3_5.txt > filtered/Borda_3_5_f.txt
filter.exe log/Plurality_3_3.txt > filtered/Plurality_3_3_f.txt
filter.exe log/Plurality_4_3.txt > filtered/Plurality_4_3_f.txt
filter.exe log/Plurality_5_3.txt > filtered/Plurality_5_3_f.txt
filter.exe log/Plurality_6_3.txt > filtered/Plurality_6_3_f.txt
filter.exe log/Plurality_7_3.txt > filtered/Plurality_7_3_f.txt
filter.exe log/Plurality_8_3.txt > filtered/Plurality_8_3_f.txt
filter.exe log/Plurality_9_3.txt > filtered/Plurality_9_3_f.txt
filter.exe log/Plurality_10_3.txt > filtered/Plurality_10_3_f.txt
filter.exe log/Plurality_3_4.txt > filtered/Plurality_3_4_f.txt
filter.exe log/Plurality_4_4.txt > filtered/Plurality_4_4_f.txt
filter.exe log/Plurality_5_4.txt > filtered/Plurality_5_4_f.txt
filter.exe log/Plurality_3_5.txt > filtered/Plurality_3_5_f.txt
filter.exe log/Schulze_3_3.txt > filtered/Schulze_3_3_f.txt
filter.exe log/Schulze_4_3.txt > filtered/Schulze_4_3_f.txt
filter.exe log/Schulze_5_3.txt > filtered/Schulze_5_3_f.txt
filter.exe log/Schulze_6_3.txt > filtered/Schulze_6_3_f.txt
filter.exe log/Schulze_7_3.txt > filtered/Schulze_7_3_f.txt
filter.exe log/Schulze_8_3.txt > filtered/Schulze_8_3_f.txt
filter.exe log/Schulze_9_3.txt > filtered/Schulze_9_3_f.txt
filter.exe log/Schulze_10_3.txt > filtered/Schulze_10_3_f.txt
filter.exe log/Schulze_3_4.txt > filtered/Schulze_3_4_f.txt
filter.exe log/Schulze_4_4.txt > filtered/Schulze_4_4_f.txt
filter.exe log/Schulze_5_4.txt > filtered/Schulze_5_4_f.txt
filter.exe log/Schulze_3_5.txt > filtered/Schulze_3_5_f.txt
